### ISSUE TITLE
create new question Activity 1 (Wonder moment)

### ISSUE THREAD

**Issue by fleurprinsen** [WELTEN/dojo-ibl#73]
Stefaan created first question but it seems after that I can only comment, not create my own new question

**Comment by Titogelo** [comment]
I don't understand your problem here @fleurprinsen. I think you were inside an activity. The only thing you can do is comment about the task or activity. You can put your questions there, actually everyone can (should) put it there. This perhaps also generates some discussions in the system as students can reply to comments.

**Comment by Titogelo** [comment]
solved

**Comment by Titogelo** [comment]
fixed #95
